name: nginx-router

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

releases:
- name: nginx-router
  version: latest
- name: consul
  version: latest

instance_groups:
- name: nginx-router
  azs: [ z1 ]
  instances: 1
  vm_type: default
  stemcell: default
  networks:
  - name: default
  jobs:
  - name: consul_agent
    release: consul
    consumes:
      consul: nil
      consul_common: {from: consul_common_link, deployment: cf}
      consul_server: {from: consul_server_link, deployment: cf}
      consul_client: {from: consul_client_link, deployment: cf}
  - name: nginx
    release: nginx-router
    properties:
      router:
        ssl_cert: "((router_ssl.certificate))"
        ssl_key: "((router_ssl.private_key))"
        enable_ssl: true
        status:
          password: "((router_status_password))"
          user: router-status
  - name: router
    release: nginx-router
    consumes:
      nats: {from: nats, deployment: cf}
    properties:
      uaa:
        clients:
          gorouter:
            secret: "((uaa_clients_gorouter_secret))"
        ssl:
          port: 8443
      nats:
        password: "((nats_password))"
  update:
    serial: false
    max_in_flight: 1

update:
  canaries: 10
  max_in_flight: 10
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
  serial: false

variables:
- name: uaa_clients_gorouter_secret
  type: password
- name: nats_password
  type: password
- name: router_status_password
  type: password
- name: router_ca
  type: certificate
  options:
    is_ca: true
    common_name: routerCA
- name: router_ssl
  type: certificate
  options:
    ca: router_ca
    common_name: routerSSL
